version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - book-storage-system-backend

  event-service:
    build:
      context: ..
      dockerfile: event-service/Dockerfile
    container_name: event-service
    environment:
      KAFKA_BROKERS: kafka:9092
      CLICKHOUSE_DSN: ${CLICKHOUSE_DSN}
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - book-storage-system-backend

volumes:
  clickhouse_data:

networks:
  book-storage-system-backend:
    external: true