version: '3.8'

services:
  api-gateway:
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile
    container_name: api_gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - book-storage-system-backend

networks:
  book-storage-system-backend:
    external: true