version: '3.8'

services:
  users_db:
    image: postgres:15-alpine
    container_name: users_db

    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_password

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users_user -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ..
      dockerfile: user-service/Dockerfile
    container_name: user_service
    environment:
      DATABASE_URL: "postgres://users_user:users_password@users_db:5432/users_db?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      users_db:
        condition: service_healthy

volumes:
  postgres_data: