version: '3.8'

services:
  books_db:
    image: postgres:15-alpine
    container_name: books_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - book-storage-system-backend

  book-service:
    build:
      context: ..
      dockerfile: book-service/Dockerfile
    container_name: book_service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKERS: "kafka:9092"
    expose:
      - "8081"
    depends_on:
      books_db:
        condition: service_healthy
    networks:
      - book-storage-system-backend

volumes:
  postgres_data:

networks:
  book-storage-system-backend:
    external: true