version: '3.8'

services:
  books_db:
    image: postgres:15-alpine
    container_name: books_db

    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: books_user
      POSTGRES_PASSWORD: books_password

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U books_user -d books_db"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - book-storage-system-backend

  book-service:
    build:
      context: ..
      dockerfile: book-service/Dockerfile
    container_name: book_service
    environment:
      DATABASE_URL: "postgres://books_user:books_password@books_db:5432/books_db?sslmode=disable"
    expose:
      - "8081"
    depends_on:
      books_db:
        condition: service_healthy
    networks:
      - book-storage-system-backend

volumes:
  postgres_data:

networks:
  book-storage-system-backend:
    external: true